### ISSUE TITLE
Microsoft.ML.Runtime.Api - Not found after installed microsoft.ml cause problem 

### ISSUE THREAD

**Issue by sefatanam** [Wintellect/DataScienceExamples#3]
I saw the youtube tutorial you got using Microsoft.ML.Runtime.Api; suggestion after writing [Column("0")] this, But I got using System.ComponentModel.DataAnnotations.Schema;-this.

Any functionality change in ML.net for getting using Microsoft.ML.Runtime.Api;  suggestion?

**Comment by jwood803** [comment]
That's from an old version of the API. For newer versions use `[LoadColumn(0)]` instead.

**Comment by sefatanam** [comment]
I understand 💯 , Thanks ☺
